### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by mb-userr** [orenavram/microbializer#25]
Hi, I tried to run your project locally, but I had so many problems with it and finally gave up. Could you please add instructions on how to run the program properly? E.g. version of python, version of libraries and step by step what commands to type and what to change in files like "CONSTANTS". Also why do you have imports from libraries which doesn't exist in PyPI?

**Comment by orenavram** [comment]
Unfortunately unless you have a computer cluster you will not be able to run it locally. Inability to run such computations locally was one of the reasons for the need of such a tool. Sorry for the inconvenience.
