### ISSUE TITLE
Cannot access tool

### ISSUE THREAD

**Issue by fmalmeida** [orenavram/microbializer#26]
Hi devs,
Tried to access the website and it seems off:

![IMG_4125](https://github.com/orenavram/microbializer/assets/7727714/fdc9d9dc-82ac-47b6-a56d-b4c2087fb260)

**Comment by orenavram** [comment]
Thanks for your message. The web server is under maintenance and will be back shortly. Feel free to contact me directly if you have any questions/issues at orenavram@gmail.com.

**Comment by fmalmeida** [comment]
Thanks for the information.

**Comment by orenavram** [comment]
Hi, the tool was moved to a different temporary location:
https://tau.evolseq.net/microbializer/
Thanks
