### ISSUE TITLE
Bad stylesheet link in result page

### ISSUE THREAD

**Issue by MaozGelbart** [orenavram/microbializer#27]
Hi, thanks for the tool!

The following line calls for a stylesheet but links to a location that doesn't exist, and this results in error 200 when the browser is trying to load the results page:
https://github.com/orenavram/microbializer/blob/3fb97f86dd21f471d6fc2d2f93b0da543e9d6fa0/cgi/microbializer_cgi.py#L60

I think this line can be safely removed. 

(on a side note, a refresh of 5 seconds is too fast and probably results in a heavy load on your servers. I'd suggest for a 30sec refresh interval)

**Comment by orenavram** [comment]
Thanks Maoz! We're actually working on a second version with more up to date technologies so we will replace the whole somewhat-old engine anyway. Dash.
