### ISSUE TITLE
Local Option

### ISSUE THREAD

**Issue by gwl2** [orenavram/microbializer#28]
Hi,
great work, thanks!
As the webserver is down, I was wondering if the tool can be installed and run locally?
This would generally be a nice thing.

best,
Gabriel

**Comment by orenavram** [comment]
Hello and thank you for using Microbializer! All the scripts are runnable on any machine with Python installed. However, the full pipeline demands significant computational resources and is therefore executed on a computer cluster on our end. For this reason, we have not provided local installation instructions. The web server is currently undergoing a major upgrade and will soon be available with new features. We appreciate your patience and sincerely apologize for any inconvenience this may cause!

**Comment by Dx-wmc** [comment]
@orenavram Could you please provide instructions for local installation? In fact, due to the need for batch processing, the online version is not as convenient as local execution when running large amounts of data. I request that you release instructions for local installation.

**Comment by shimooper** [comment]
Hi, we're working on adjusting the code to enable local installation, and will update when it's ready.
Anyway, the webserver supports up to 2,000 genomes as input data.
